name = "Autcraft Modpack"
author = "Stonewall0210"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1fe616ca3ec243f77ac70efaf7a98fa533ede0d885617238148c4c1787974176"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
