name = "Autcraft Modpack"
author = "Stonewall0210"
version = "1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5865fb9d246a800deb72ec3052ad7561134a591fcec955f1d63802cbf58726a9"

[versions]
fabric = "0.11.6"
minecraft = "1.17.1"

[options]
acceptable-game-versions = ["1.17"]
