name = "Blur (Fabric)"
filename = "Blur-2.3.0-1.17+fabric.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com//data/NK39zBp2/versions/2.3.0/Blur-2.3.0-1.17+fabric.jar"
hash-format = "sha512"
hash = "b60deb812079f143cb24b4d36c5b72b2cc8a03678689868726d50f477f82f9a09cc9f358e7c964c49e2115497ca7e269f70732daae82b6488eafc8af68c858fe"

[update]
[update.modrinth]
mod-id = "NK39zBp2"
version = "Uxk0Zani"

[option]
default = false
optional = true
description = "Lets you customise the normally transparent black GUI background shown when in inventories or in the pause menu by changing its colour, making it a gradient, or blurring what's behind it."