name = "Canvas Renderer"
filename = "canvas-fabric-mc117-1.0.2202.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3529/363/canvas-fabric-mc117-1.0.2202.jar"
hash-format = "murmur2"
hash = "141570600"

[update]
[update.curseforge]
file-id = 3529363
project-id = 318440
release-channel = "beta"

[option]
optional = true
description = "An alternative shader and optimisation mod, incompatible with Sodium and Iris."
