name = "Continuity"
filename = "continuity-1.0.1+1.17.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/1IjD5062/versions/1.0.1+1.17/continuity-1.0.1+1.17.jar"
hash-format = "sha512"
hash = "a639b9c76a8d8aad35b1f918079cfffc748f4c8d1748dc3f5fdd143fccb5064b86fb3216d44fe3fe804635dd4411298ef6203c105d787a9c9c00abb61f93774d"

[update]
[update.modrinth]
mod-id = "1IjD5062"
version = "6JEV45oM"

[option]
default = false
optional = true
description = "A connected textures mod that mirrors the MCPatcher/Optifine format. (This exact mod isn't on the approved mod list yet but should be allowed on AC)"