name = "Fabric API"
filename = "fabric-api-0.41.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3494/349/fabric-api-0.41.0+1.17.jar"
hash-format = "murmur2"
hash = "2846834524"

[update]
[update.curseforge]
file-id = 3494349
project-id = 306612
release-channel = "beta"

[option]
optional = false
description = "This API mod is the key around many if not all Fabric mods. Any setup chosen here would break without this mod, and as such it is essentially not optional."
default = true
