name = "Fabric API"
filename = "fabric-api-0.40.0+1.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3446/268/fabric-api-0.40.0+1.17.jar"
hash-format = "murmur2"
hash = "1579203170"

[update]
[update.curseforge]
file-id = 3446268
project-id = 306612
release-channel = "beta"

[option]
default = true
optional = false
description = "This API mod is the key around many if not all Fabric mods. Any setup chosen here would break without this mod, and as such it is essentially not optional."