name = "FabricSkyboxes"
filename = "fabricskyboxes-1.17-0.5.2.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YBz7DOs8/versions/0.5.2/fabricskyboxes-1.17-0.5.2.jar"
hash-format = "sha512"
hash = "c776a5f8371dde1988213f00912923c74564b2459dfbfabbfd1f87738b3ae13fdc39ce762458bec312958a1584cc1b911215d7f5e550e02481498b6f5804e1c4"

[update]
[update.modrinth]
mod-id = "YBz7DOs8"
version = "QZ458aNV"

[option]
default = false
optional = true
description = "A mod allowing for custom skyboxes, allowing for pretty night skies instead of black with white dots. Uses its own format."