name = "Iris Shaders"
filename = "iris-mc1.17-1.1.1.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/YL57xq9U/versions/mc1.17-v1.1.1/iris-mc1.17-1.1.1.jar"
hash-format = "sha512"
hash = "18aa480d8503cf98e87bc37ba734ca61b2f1c85dd92a52e5501b4e2a5d8fe17dba1de9b748155c054cb6a3f31e1fc9643d4491413ad7cf7f20ba90aec338cb76"

[update]
[update.modrinth]
mod-id = "YL57xq9U"
version = "lAEtBzCu"

[option]
default = false
optional = true
description = "Iris allows support for Optifine shaders without Optifine. This mod is less likely to cause imcompatibilities with mods, and uses Sodium for better performance than Optifine, with the trade off of less-than-optimal compatibility with Optifine shaders. Basically, it works good enough for most people, but isn't completely perfect.\nIncompatible with:\n- Sodium (Sodium is supplied with this mod, there is no need to select them both)\n- Optifine (Sodium is incompatible with Optifine, and never will be compatible. Also why'd you want to use Optifine and Iris at the same time?)"