name = "Item Scroller"
filename = "itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3379/264/itemscroller-fabric-1.17.1-0.15.0-dev.20210707.005506.jar"
hash-format = "murmur2"
hash = "2166710212"

[update]
[update.curseforge]
file-id = 3379264
project-id = 242064
release-channel = "beta"

[option]
default = false
optional = true
description = "Adds many new shortcuts for inventory GUIs allowing you to move items around much quicker than usual. Please be careful not to drop an excessive amount of items onto the ground, particularly when mass crafting, as this can cause lag."