name = "LambDynamicLights"
filename = "lambdynamiclights-2.0.2+1.17.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/yBW8D80W/versions/2.0.2+1.17/lambdynamiclights-2.0.2+1.17.jar"
hash-format = "sha512"
hash = "87b5a08e007c2fa387ca58c866e2c6db6d1335a8c7878d2c5a2c1df4058db3aeab99bdb214b28fa7e77b6094b7c3ab5c37370195696154ccb4ba1c1411468308"

[update]
[update.modrinth]
mod-id = "yBW8D80W"
version = "GiwO5rBh"

[option]
default = false
optional = true
description = "Ports the dynamic lights feature from optifine to soduim installs.\nIncompatible with optifine."