name = "LazyDFU"
filename = "lazydfu-0.1.2.jar"
side = "both"

[download]
url = "https://cdn.modrinth.com/data/hvFnDODi/versions/0.1.2/lazydfu-0.1.2.jar"
hash-format = "sha512"
hash = "20b1cd3e62051c7d7498ecdc49912acb918fc4748d469c67c078cc97197289760e64b9339a4d4a03d175f648c8be8601d131776a9a6bdb8832cecdda6fc46498"

[update]
[update.modrinth]
mod-id = "hvFnDODi"
version = "C6e265zK"

[option]
default = false
optional = true
description = "Cuts down the game start time by a lot by removing the one thing that takes the longest time in vanilla: the Data Fixer Upper.\nIn short, the DFU is what controlls the conversion from old game versions to new game versions. The problem with this is that it then spends like 3 hours every game startup preparing for updating worlds from every game version, and then ends up not using it because you play on Autcraft and then nothing else.\nWith this, the game skips the DFU, and only loads it when you actually need to use it. It means you get a lag spike when loading a world that needs to be updated, but that's just the DFU initialising.\n\nI recommend you use this."