name = "Mod Menu"
filename = "modmenu-2.0.12.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com//data/mOgUt4GM/versions/2.0.12/modmenu-2.0.12.jar"
hash-format = "sha512"
hash = "5d7f921acd3712b7db606e273fbfe73bee532b63858be844e7d3659b71cc533d8580d2c28dc264df8ac1382452873ec3d1b11e3411377c1aa5bccc1c9fab332c"

[update]
[update.modrinth]
mod-id = "mOgUt4GM"
version = "9xECQHnM"

[option]
optional = true
description = "Displays the mods you have installed, like Forge does, and lets you edit the configs of many mods. Must have in my opinion."
