name = "Optifine"
filename = "optifabric-1.11.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3422/922/optifabric-1.11.20.jar"
hash-format = "murmur2"
hash = "4066970355"

[update]
[update.curseforge]
file-id = 3422922
project-id = 322385
release-channel = "beta"

[option]
default = false
optional = true
description = "WARNING: Optifine breaks a lot of compatibility with most of the other mods on this list so please carefully read the incompatible mod list before installing.\n\nThe modding classic: Optifine.\nPlease note that downloading this mod will only download the mod called Optifabric, and I cannot provide Optifine itself in this pack due to it's license. After downloading you will need to download Optifine and put it in your mods folder otherwise the game will refuse to load."