name = "Pretty Capes"
filename = "prettycapes-1.2-Fabric1.17.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/VNmsFeXY/versions/1.2/prettycapes-1.2-Fabric1.17.jar"
hash-format = "sha512"
hash = "9a3196d243b45e1a0b2f515424ed2e221a1a93cc121a2ab163af0670caa6d3f69afc1e828d4f90b8ed90be676ba9780193728b45fb5bfc7b907591f1ac27eca3"

[update]
[update.modrinth]
mod-id = "VNmsFeXY"
version = "UvvBfU6h"

[option]
default = false
optional = true
description = "Makes capes always render as their elytra version even if an elytra isn't being worn."