name = "Skin Layers 3D (Fabric/Forge)"
filename = "3dSkinLayers-Fabric-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3489/973/3dSkinLayers-Fabric-1.1.1.jar"
hash-format = "murmur2"
hash = "3763522784"

[update]
[update.curseforge]
file-id = 3489973
project-id = 521480
release-channel = "beta"

[option]
default = false
optional = true
description = "Renders the usually flat second layer of player skins as a 3D model."