name = "Sodium"
filename = "sodium-fabric-mc1.17.1-0.3.2+build.7.jar"
side = "client"

[download]
url = "https://cdn.modrinth.com/data/AANobbMI/versions/mc1.17.1-0.3.2/sodium-fabric-mc1.17.1-0.3.2+build.7.jar"
hash-format = "sha512"
hash = "11076f2aba94a421fd2a1514a88bde85717b6cab5614dbb59094fcae931446977a6c1ea3929f3896bc2ca226b2386d54264cc3c39376b78f929786429d82b4ce"

[update]
[update.modrinth]
mod-id = "AANobbMI"
version = "xuWxRZPd"

[option]
default = false
optional = true
description = "If you only use Optifine for the performance boost, don't use Optfine; use Sodium. Sodium basically achives the same effect, but has the added bonus of:\n1. Increase performance a whole lot more than Optifine (depending on your computer)\n2. Doesn't break as many mods.\nThe extra performance from Sodium is very much worth missing out on the 1 or 2 Optifine features that don't have fabric alternatives.\n\nIncompatible with:\n- Iris (Sodium is included in Iris)\n- Optifine (Sodiums method of performance improvments will break with Optifine, and there is no reason for you to use Optfine if you have Sodium)"