name = "Wavey Capes"
filename = "WaveyCapes-fabric-1.0.4-mc1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3516/536/WaveyCapes-fabric-1.0.4-mc1.17.1.jar"
hash-format = "murmur2"
hash = "2576562657"

[update]
[update.curseforge]
file-id = 3516536
project-id = 521594
release-channel = "beta"

[option]
optional = true
description = "Makes capes be wavey!"
