name = "Xaero's World Map"
filename = "XaerosWorldMap_1.18.1_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3512/813/XaerosWorldMap_1.18.1_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "4250548443"

[update]
[update.curseforge]
file-id = 3512813
project-id = 317780
release-channel = "beta"

[option]
optional = true
description = "Map mod that works with Xaero's Minimap. They map out the area around you in real-time and let you set waypoints to remember locations. Do not use this in competitive minigames such as bed wars and H&S."
