name = "Xaero's Minimap (Fair-play Edition)"
filename = "Xaeros_Minimap_FP21.21.0_Fabric_1.17.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3516/185/Xaeros_Minimap_FP21.21.0_Fabric_1.17.1.jar"
hash-format = "murmur2"
hash = "3228668635"

[update]
[update.curseforge]
file-id = 3516185
project-id = 263466
release-channel = "beta"

[option]
optional = true
description = "Map mod that works with Xaero's World Map. They map out the area around you in real-time and let you set waypoints to remember locations. Do not use this in competitive minigames such as bed wars and H&S."
